# Generated by Django 4.2.7 on 2023-11-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name of article: ')),
                ('anonse', models.CharField(max_length=250, verbose_name='Anons: ')),
                ('absolute_text', models.TextField(verbose_name='Absolute article text: ')),
                ('date', models.DateTimeField(verbose_name='Date of public: ')),
            ],
        ),
    ]
