# Generated by Django 4.2.7 on 2023-11-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='absolute_text',
            field=models.TextField(verbose_name='Absolute article text '),
        ),
        migrations.AlterField(
            model_name='articles',
            name='anonse',
            field=models.CharField(max_length=250, verbose_name='Anonse '),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(verbose_name='Date of public '),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Name of article '),
        ),
    ]
